### ISSUE TITLE
Cannot Copy/Paste/Select All text from fields when adding scenes

### ISSUE THREAD

**Issue by TarasOsiris** [zasadnyy/unity-editor-utilities#1]
Cannot Copy/Paste text from fields when adding scenes (CTRL-C, CRTL-V, CTRL-A)

![editor](https://cloud.githubusercontent.com/assets/3141378/6918049/8b69472e-d7aa-11e4-9f5a-06e6f45d4045.png)

**Comment by zasadnyy** [comment]
Thanks for a request, I'll work on it for a next release.

**Comment by zasadnyy** [comment]
Fixed.
